alias gst "git status"
alias gpo "git push origin"
alias gpull "git pull"
alias gco "git checkout"
alias gca "git commit -avm"
alias gc "git commit -v"
alias gignored "git ls-files -o -i --exclude-standard"
alias gg "git log --oneline --abbrev-commit --all --graph --decorate --color"
alias gaa "git add --all ."

alias master "git checkout master"
alias staging "git checkout staging"
